### ISSUE TITLE
Generated date should not include quotes

### ISSUE THREAD

**Issue by wvanlit** [bbbco/insomnia-plugin-faker#12] opened 2022-07-15 12:58 UTC
When using options from Faker>Date that generate an ISO date string, it will always add double quotes around the result. This makes it hard to use in environments and requests.

![image](https://user-images.githubusercontent.com/44299782/179227457-110c2570-b1d6-4a4a-8378-d2101d122e5b.png)
 
If possible either remove the quotes, or add a modifier option to remove the quotes.

**Comment by bbbco** [comment] 2022-09-06 16:07
There is a larger issue here, as there are several different Faker types that return quoted strings (Date, etc), array objects (Address > GPS Cordinates, Colors, DataType>Array, etc), and objects (DataType>JSON Object, Science, etc) which the JSON linter cannot easily parse.

I added a PR to insomnia to fix this in the regular interface: https://github.com/Kong/insomnia/pull/5136 
Note, there is not yet a fix for handling this in environments. I am currently working on this problem.

**Comment by JwanKhalaf** [comment] 2022-11-12 23:18
This issue is a show stopper in my case. Is there a work-around one could do until the issue is fixed?

**Comment by bbbco** [comment] 2022-11-13 01:16
Hey @JwanKhalaf , we are still waiting for https://github.com/Kong/insomnia/pull/5136 to be pulled into the latest release. It has been verified and approved, just waiting for the PR to be merged in. Then, this issue can be marked as resolved in the latest insomnia release.

Feel free to comment on that PR requesting it to be merged in if you need this!

**Comment by bbbco** [comment] 2022-11-15 18:07
The PR was merged in and will go into the latest version of Insomnia!

**Closed by bbbco** 2022-11-15 18:07 UTC

**Comment by bbbco** [comment] 2022-11-17 20:59
This is now available in the latest Insomnia beta build! https://insomnia.rest/changelog#2022.7.0-beta.5
